server/main/urls.py
from django.urls import path

from .views import (
    about, contacts, main
)

app_name = 'main'


urlpatterns = [
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('', main, name='main'),
]

server/server/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('categories/', include('products.urls.categories')),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

server/products/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(
        blank=True,
        null=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(
        upload_to='products',
        blank=True,
        null=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    description = models.TextField(
        blank=True,
        null=True,
    )
    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

server/products/forms/categories.py
from django import forms
from products.models import Category


class CategoryForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        widget=forms.widgets.TextInput(
            attrs={'class': 'form-field'}
        )
    )
    description = forms.CharField(
        required=False,
        widget=forms.widgets.Textarea(
            attrs={'class': 'form-field'}
        )
    )


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']
        widgets = {
            'name': forms.widgets.TextInput(
                attrs={'class': 'form-field'}
            ),
            'description': forms.widgets.Textarea(
                attrs={'class': 'form-field'}
            ),
        }

server/products/forms/products.py
from django import forms

from products.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name', 'image', 'category', 
            'description', 'cost'
        )

server/products/views/categories.py
from django.urls import reverse
from django.shortcuts import (
    render, redirect, get_object_or_404
)

from products.models import Category
from products.forms import CategoryForm, CategoryModelForm


def category_create(request):
    form = CategoryModelForm()
    if request.method == 'POST':
        form = CategoryModelForm(
            data=request.POST,
            files=request.FILES,
        )
        if form.is_valid():
            form.save()
            # Category.objects.create(
            #     name=form.cleaned_data.get('name')
            # )
            return redirect('products:main')

    return render(
        request,
        'categories/create.html',
        {'form': form}
    )


def category_update(request, pk):
    obj = get_object_or_404(Category, pk=pk)

    form = CategoryModelForm(
        instance=obj
    )

    if request.method == 'POST':
        form = CategoryModelForm(
            request.POST,
            files=request.FILES,
            instance=obj,
        )

        if form.is_valid():
            form.save()

            return redirect('products:main')

    return render(
        request,
        'categories/update.html',
        {'form': form}
    )


def category_delete(request, pk):
    obj = get_object_or_404(Category, pk=pk)
    
    if request.method == 'POST':
        obj.delete()

        return redirect('products:main')

    return render(
        request,
        'categories/delete.html',
        {'object': obj}
    )


def category_list(request):
    return render(
        request,
        'categories/index.html',
        {'object_list': Category.objects.all()}
    )


def category_detail(request, pk):
    obj = get_object_or_404(Category, pk=pk)
    return render(
        request,
        'categories/detail.html',
        {'object': obj}
    )

server/products/views/products.py
import json
from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.http import JsonResponse

from products.models import Product
from products.forms import ProductForm


def product_rest_list(request):
    data = []
    object_list = Product.objects.all()

    for itm in object_list:
        data.append(
            {
                'id': itm.id,
                'name': itm.name,
                'image': itm.image.url if itm.image else None,
                'category': itm.category.name,
                'description': itm.description,
                'cost': itm.cost,
                'created': itm.created,
                'modified': itm.modified,
            }
        )

    return JsonResponse({'results': data})


def product_create(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(
            data=request.POST,
            files=request.FILES
        )
        if form.is_valid():
            form.save()
            # Category.objects.create(
            #     name=form.cleaned_data.get('name')
            # )
            return redirect('products:main')

    return render(
        request,
        'categories/create.html',
        {'form': form}
    )


def product_update(request, pk):
    obj = get_object_or_404(Product, pk=pk)

    form = ProductForm(
        instance=obj
    )

    if request.method == 'POST':
        form = ProductForm(
            request.POST,
            files=request.FILES,
            instance=obj,
        )

        if form.is_valid():
            form.save()

            return redirect('products:main')

    return render(
        request,
        'categories/update.html',
        {'form': form}
    )


def product_delete(request, pk):
    obj = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        obj.delete()

        return redirect('products:main')

    return render(
        request,
        'categories/delete.html',
        {'object': obj}
    )


def product_list(request):
    # with open('products/fixtures/data/data.json') as file:
    #     return render(
    #         request, 
    #         'products/index.html',
    #         {'object_list': json.load(file)}
    #     )
    return render(
        request,
        'products/index.html',
        {'object_list': Product.objects.all()[:3]}
    )


def product_detail(request, pk):
    # with open('products/fixtures/data/data.json') as file:
    #     return render(
    #         request, 
    #         'products/detail.html',
    #         {'object': json.load(file)[pk]}
    #     )
    obj = get_object_or_404(Product, pk=pk)
    return render(
        request,
        'products/detail.html',
        {'object': obj}
    )

server/products/templates/categories/create.html
{% extends 'server/master.html' %}

{% block page_title %}
Product detail
{% endblock %}

{% block page_content %}
{% include 'server/form.html' with form=form %}
{% endblock %}

server/products/templates/categories/delete.html
{% extends 'server/master.html' %}

{% block page_title %}
Delete item
{% endblock %}

{% block page_content %}
<form method="post">
    {% csrf_token %}
    <span>Запись {{ object.name }} будет удалена.</span>
    <input type="submit">
</form>
{% endblock %}

server/products/templates/categories/detail.html
{% extends 'server/master.html' %}

{% load static %}

{% block page_static %}
<link rel="stylesheet" href="{% static 'products/css/detail.css' %}">
<link rel="stylesheet" href="{% static 'products/css/list.css' %}">
{% endblock %}

{% block page_title %}
Product detail
{% endblock %}

{% block page_content %}
<div class="product">
    <h1 class="product__name">
        {{ object.name }}
    </h1>
    <span class="product__description">
        {{ object.description }}
    </span>
</div>

<div class="products">
    {% for itm in object.product_set.all %}
        {% include 'server/product.html' with image=itm.image name=itm.name description=itm.description cost=itm.cost id=itm.id %}
    {% endfor %}
</div>
{% endblock %}

server/products/templates/categories/index.html
{% extends 'server/master.html' %}

{% load static %}

{% block page_static %}
<link rel="stylesheet" href="{% static 'products/css/list.css' %}">
{% endblock %}

{% block page_title %}
Product list
{% endblock %}

{% block page_content %}
<h1>Product List</h1>
<div class="categories">
    {% for itm in object_list %}
    <div class="categories__item">
        <span class="categories__item-name">
            {{ itm.name }}
        </span>
        <span class="categories__item-description">
            {{ itm.description }}
        </span>
        <a href="{% url 'categories:detail' pk=itm.id %}" class="categories__item-link">Перейти</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

server/products/templates/categories/update.html
{% extends 'server/master.html' %}

{% block page_title %}
Update item
{% endblock %}

{% block page_content %}
{% include 'server/form.html' with form=form %}
{% endblock %}