server/main/urls.py
from django.urls import path

from .views import (
    about, contacts, main
)

app_name = 'main'


urlpatterns = [
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('', main, name='main'),
]

server/server/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('categories/', include('products.urls.categories')),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

server/products/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(
        blank=True,
        null=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(
        upload_to='products',
        blank=True,
        null=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    description = models.TextField(
        blank=True,
        null=True,
    )
    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
    )
    created = models.DateTimeField(
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

server/products/forms/categories.py
from django import forms
from products.models import Category


class CategoryForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        widget=forms.widgets.TextInput(
            attrs={'class': 'form-field'}
        )
    )
    description = forms.CharField(
        required=False,
        widget=forms.widgets.Textarea(
            attrs={'class': 'form-field'}
        )
    )


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']
        widgets = {
            'name': forms.widgets.TextInput(
                attrs={'class': 'form-field'}
            ),
            'description': forms.widgets.Textarea(
                attrs={'class': 'form-field'}
            ),
        }

server/products/forms/products.py
from django import forms

from products.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name', 'image', 'category', 
            'description', 'cost'
        )

server/products/views/categories.py
from django.urls import reverse
from django.shortcuts import (
    render, redirect, get_object_or_404
)

from products.models import Category
from products.forms import CategoryForm, CategoryModelForm


def category_create(request):
    form = CategoryModelForm()
    if request.method == 'POST':
        form = CategoryModelForm(
            data=request.POST,
            files=request.FILES,
        )
        if form.is_valid():
            form.save()
            # Category.objects.create(
            #     name=form.cleaned_data.get('name')
            # )
            return redirect('products:main')

    return render(
        request,
        'categories/create.html',
        {'form': form}
    )


def category_update(request, pk):
    obj = get_object_or_404(Category, pk=pk)

    form = CategoryModelForm(
        instance=obj
    )

    if request.method == 'POST':
        form = CategoryModelForm(
            request.POST,
            files=request.FILES,
            instance=obj,
        )

        if form.is_valid():
            form.save()

            return redirect('products:main')

    return render(
        request,
        'categories/update.html',
        {'form': form}
    )


def category_delete(request, pk):
    obj = get_object_or_404(Category, pk=pk)
    
    if request.method == 'POST':
        obj.delete()

        return redirect('products:main')

    return render(
        request,
        'categories/delete.html',
        {'object': obj}
    )


def category_list(request):
    return render(
        request,
        'categories/index.html',
        {'object_list': Category.objects.all()}
    )


def category_detail(request, pk):
    obj = get_object_or_404(Category, pk=pk)
    return render(
        request,
        'categories/detail.html',
        {'object': obj}
    )

server/products/views/products.py
import json
from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.http import JsonResponse

from products.models import Product
from products.forms import ProductForm


def product_rest_list(request):
    data = []
    object_list = Product.objects.all()

    for itm in object_list:
        data.append(
            {
                'id': itm.id,
                'name': itm.name,
                'image': itm.image.url if itm.image else None,
                'category': itm.category.name,
                'description': itm.description,
                'cost': itm.cost,
                'created': itm.created,
                'modified': itm.modified,
            }
        )

    return JsonResponse({'results': data})


def product_create(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(
            data=request.POST,
            files=request.FILES
        )
        if form.is_valid():
            form.save()
            # Category.objects.create(
            #     name=form.cleaned_data.get('name')
            # )
            return redirect('products:main')

    return render(
        request,
        'categories/create.html',
        {'form': form}
    )


def product_update(request, pk):
    obj = get_object_or_404(Product, pk=pk)

    form = ProductForm(
        instance=obj
    )

    if request.method == 'POST':
        form = ProductForm(
            request.POST,
            files=request.FILES,
            instance=obj,
        )

        if form.is_valid():
            form.save()

            return redirect('products:main')

    return render(
        request,
        'categories/update.html',
        {'form': form}
    )


def product_delete(request, pk):
    obj = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        obj.delete()

        return redirect('products:main')

    return render(
        request,
        'categories/delete.html',
        {'object': obj}
    )


def product_list(request):
    # with open('products/fixtures/data/data.json') as file:
    #     return render(
    #         request, 
    #         'products/index.html',
    #         {'object_list': json.load(file)}
    #     )
    return render(
        request,
        'products/index.html',
        {'object_list': Product.objects.all()[:3]}
    )


def product_detail(request, pk):
    # with open('products/fixtures/data/data.json') as file:
    #     return render(
    #         request, 
    #         'products/detail.html',
    #         {'object': json.load(file)[pk]}
    #     )
    obj = get_object_or_404(Product, pk=pk)
    return render(
        request,
        'products/detail.html',
        {'object': obj}
    )

server/server/templates/server/form.html
<form method="POST" enctype="multipart/form-data">
    {% for err in form.not_field_errors %}
    <div class="alert alert-danger">
        <span>{{ err }}</span>
    </div>
    {% endfor %}

    {% csrf_token %}
    {% for field in form %}
    <div class="field-group">
        <label for="{{ field.name }}">{{ field.label }}</label>
        {{ field }}

        {% for err in field.errors %}
        <small class="field_error">{{ err }}</small>
        {% endfor %}

    </div>
    {% endfor %}
    <input type="submit">
</form>

server/server/templates/server/master.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>
        {% block page_title %}{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static '/main/css/index.css' %}" />
    {% block page_static %}{% endblock %}
</head>

<body>
    <div class="page">
        <header class="page__header">
            <nav class="page__navigation">
                <ul class="navigation-list">
                    <li class="navigation-list__item">
                        <span class="navigation-list__item-text">
                            Главная
                        </span>
                        <a href="{% url 'main:main' %}" class="navigation-list__item-link">
                        </a>
                    </li>
                    <li class="navigation-list__item">
                        <span class="navigation-list__item-text">
                            Каталог
                        </span>
                        <a href="{% url 'products:main' %}" class="navigation-list__item-link">
                        </a>
                    </li>
                    <li class="navigation-list__item">
                        <span class="navigation-list__item-text">
                            О проекте
                        </span>
                        <a href="{% url 'main:about' %}" class="navigation-list__item-link">
                        </a>
                    </li>
                    <li class="navigation-list__item">
                        <span class="navigation-list__item-text">
                            Контакты
                        </span>
                        <a href="{% url 'main:contacts' %}" class="navigation-list__item-link">
                        </a>
                    </li>
                </ul>
            </nav>
        </header>
        <div class="page__content">
            {% block page_content %}{% endblock %}
        </div>
        <footer class="page__footer">
            <span class="page__copyright">
                © GeekBrains
            </span>
        </footer>
    </div>
    {% block page_scripts %}{% endblock %}
</body>

</html>

server/server/templates/server/product.html
{% load static %}

<div class="products__item">
    {% if image %}
    <img class="products__item-image" src="{{ image.url }}" alt="{{ name }}">
    {% else %}
    <img class="products__item-image products__item-image_empty" src="{% static 'products/images/empty.png' %}" alt="empty">
    {% endif %}
    <span class="products__item-name">
        {{ name|default:"По умолчанию"|title }}
    </span>
    <span class="products__item-description">
        {{ description|safe }}
    </span>
    {% if cost %}
    <span class="products__item-cost">
        {{ cost }}
    </span>
    {% else %}
    <span class="products__item-cost products__item-cost_empty">
        Значение отсутствует
    </span>
    {% endif %}
    <a href="{% url 'products:detail' pk=id %}" class="products__item-link">
        Ссылка на {{ name|lower }}
    </a>
</div>